### ISSUE TITLE
PCL tracking with Kinect2Grabber

### ISSUE THREAD

**Issue by alex292** [UnaNancyOwen/KinectGrabber#11]
Hello,

first of all thank your for providing documentation and pre-built binaries for PCL and writing the Kinect v2 Grabber.

We are having troubles using the PCL tracking sample in combination with your Kinect2Grabber. We have installed PCL using your pre-built binaries (http://unanancyowen.com/?p=1255&lang=en) and the Kinect2Grabber sample runs properly.

We modified the tracking_smaple.cpp from PCL (https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/tracking/tracking_sample.cpp), but we can't get it running. 
It throws an access violation exception as soon as the programm starts (see image).

![error](https://cloud.githubusercontent.com/assets/3793004/7349015/57714d34-ecf6-11e4-959e-787da437639d.png)

What are we doing wrong?

Cheers
Daniel Kauth & Alexander Hendrich (Students at TU Darmstadt, Germany)

**Comment by UnaNancyOwen** [comment]
Hi alex292,

Sorry, I don't know the cause of this problem.
Can you send a pcd file that was used to input?

**Comment by alex292** [comment]
Thank you for your response. We are still having troubles, but we managed to solve the problem stated above. It seems like the Kinect or the Kinect2Grabber doesn't provide a XYZRGBA-Signal. We solved it by only working with XYZRGB, which seems to work.
